name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.11']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 6.0.11'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.11'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build BadBroker --configuration Release --no-restore
      - name: Test
        run: dotnet test BadBroker.Unit.Tests --no-restore --verbosity normal